name: FSharp.Data.SqlClient 'Actions' CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.402
    - name: Install dependencies
      run: 
        dotnet restore tools
        dotnet tool install paket
        dotnet paket restore
    - name: Build
      run: 
        build
